package com.frikinzi.creatures.registry;

import com.frikinzi.creatures.Creatures;
import com.frikinzi.creatures.client.block.CreaturesBlocks;
import com.frikinzi.creatures.item.*;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.material.Fluids;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class CreaturesItems {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Creatures.MODID);
    public static final DeferredRegister<CreativeModeTab> TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Creatures.MODID);

    public static final RegistryObject<Item> KOI_BUCKET = ITEMS.register("bucket_of_koi", () -> new CreaturesFishBucket(() -> CreaturesEntities.KOI.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> DOTTYBACK_BUCKET = ITEMS.register("bucket_of_dottyback", () -> new CreaturesFishBucket(() -> CreaturesEntities.DOTTYBACK.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> PIKE_BUCKET = ITEMS.register("bucket_of_pike", () -> new CreaturesFishBucket(() -> CreaturesEntities.PIKE.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> GUPPY_BUCKET = ITEMS.register("bucket_of_guppy", () -> new CreaturesFishBucket(() -> CreaturesEntities.GUPPY.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> AROWANA_BUCKET = ITEMS.register("bucket_of_arowana", () -> new CreaturesFishBucket(() -> CreaturesEntities.AROWANA.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> SHRIMP_BUCKET = ITEMS.register("bucket_of_shrimp", () -> new CreaturesFishBucket(() -> CreaturesEntities.SHRIMP.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> GOURAMI_BUCKET = ITEMS.register("bucket_of_gourami", () -> new CreaturesFishBucket(() -> CreaturesEntities.GOURAMI.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> GOLDFISH_BUCKET = ITEMS.register("bucket_of_goldfish", () -> new CreaturesFishBucket(() -> CreaturesEntities.GOLDFISH.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> RANCHU_BUCKET = ITEMS.register("bucket_of_ranchu", () -> new CreaturesFishBucket(() -> CreaturesEntities.RANCHU.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> FIRE_GOBY_BUCKET = ITEMS.register("bucket_of_fire_goby", () -> new CreaturesFishBucket(() -> CreaturesEntities.FIRE_GOBY.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> BLUE_TANG_BUCKET = ITEMS.register("bucket_of_blue_tang", () -> new CreaturesFishBucket(() -> CreaturesEntities.BLUE_TANG.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> TROUT_BUCKET = ITEMS.register("bucket_of_trout", () -> new CreaturesFishBucket(() -> CreaturesEntities.TROUT.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> FLAME_ANGELFISH_BUCKET = ITEMS.register("bucket_of_flame_angelfish", () -> new CreaturesFishBucket(() -> CreaturesEntities.FLAME_ANGELFISH.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> RED_SNAPPER_BUCKET = ITEMS.register("bucket_of_red_snapper", () -> new CreaturesFishBucket(() -> CreaturesEntities.RED_SNAPPER.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> TIGER_BARB_BUCKET = ITEMS.register("bucket_of_tigerbarb", () -> new CreaturesFishBucket(() -> CreaturesEntities.TIGERBARB.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> ARAPAIMA_BUCKET = ITEMS.register("bucket_of_arapaima", () -> new CreaturesFishBucket(() -> CreaturesEntities.ARAPAIMA.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> PIRANHA_BUCKET = ITEMS.register("bucket_of_piranha", () -> new CreaturesFishBucket(() -> CreaturesEntities.PIRANHA.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> TAMBAQUI_BUCKET = ITEMS.register("bucket_of_tambaqui", () -> new CreaturesFishBucket(() -> CreaturesEntities.TAMBAQUI.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> ELEPHANTNOSE_BUCKET = ITEMS.register("bucket_of_elephant_nose", () -> new CreaturesFishBucket(() -> CreaturesEntities.ELEPHANTNOSE.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> CLOWNFISH_BUCKET = ITEMS.register("bucket_of_clownfish", () -> new CreaturesFishBucket(() -> CreaturesEntities.CLOWNFISH.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> LOOKDOWN_BUCKET = ITEMS.register("bucket_of_lookdown", () -> new CreaturesFishBucket(() -> CreaturesEntities.LOOKDOWN.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> SEADRAGON_BUCKET = ITEMS.register("bucket_of_seadragon", () -> new CreaturesFishBucket(() -> CreaturesEntities.SEADRAGON.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> MANTIS_SHRIMP_BUCKET = ITEMS.register("bucket_of_mantis_shrimp", () -> new CreaturesFishBucket(() -> CreaturesEntities.MANTIS_SHRIMP.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> TRUMPETFISH_BUCKET = ITEMS.register("bucket_of_trumpetfish", () -> new CreaturesFishBucket(() -> CreaturesEntities.TRUMPETFISH.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> PARROTFISH_BUCKET = ITEMS.register("bucket_of_parrotfish", () -> new CreaturesFishBucket(() -> CreaturesEntities.PARROTFISH.get(), () -> Fluids.WATER, new Item.Properties()));
    public static final RegistryObject<Item> TETRA_BUCKET = ITEMS.register("bucket_of_tetra", () -> new CreaturesFishBucket(() -> CreaturesEntities.TETRA.get(), () -> Fluids.WATER, new Item.Properties()));

    public static final RegistryObject<Item> FF_GUIDE = ITEMS.register("ff_guide", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> GUPPY_TAIL = ITEMS.register("guppy_tail",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> FISHING_BIN = ITEMS.register("fishing_bin", () -> new FishStorageBinItem(new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> GOLDFISH = ITEMS.register("item_goldfish",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CRAB_PINCERS = ITEMS.register("crab_pincers",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> DUCK_FEATHER = ITEMS.register("duck_feather",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> BIRD_OF_PREY_FEATHER = ITEMS.register("bird_of_prey_feather",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAVEN_FEATHER = ITEMS.register("raven_feather",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> PARROT_FEATHER = ITEMS.register("parrot_feather",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> PEAFOWL_FEATHER = ITEMS.register("peafowl_feather",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> BIRD_CARRIER = ITEMS.register("bird_carrier",
            () -> new BirdCarrierItem(new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> CRITTER_KEEPER = ITEMS.register("critter_keeper",
            () -> new CritterKeeperItem(new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> FISH_FOOD = ITEMS.register("fish_food",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> ALGAE_WAFER = ITEMS.register("algae_wafer",
            () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> FISHING_NET = ITEMS.register("fishingnet",
            () -> new FishNetItem(new Item.Properties().stacksTo(1)));
    static int i = 0;
    public static final RegistryObject<Item> LOVEBIRD_EGG = ITEMS.register("lovebird_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> SPOONBILL_EGG = ITEMS.register("spoonbill_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> KAKAPO_EGG = ITEMS.register("kakapo_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> MANDARIN_DUCK_EGG = ITEMS.register("mandarin_duck_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> RAVEN_EGG = ITEMS.register("raven_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> DOVE_EGG = ITEMS.register("dove_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> RED_KITE_EGG = ITEMS.register("red_kite_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> GOLDEN_EAGLE_EGG = ITEMS.register("golden_eagle_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> STELLERS_SEA_EAGLE_EGG = ITEMS.register("stellers_sea_eagle_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> GYRFALCON_EGG = ITEMS.register("gyrfalcon_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> LORIKEET_EGG = ITEMS.register("lorikeet_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> CONURE_EGG = ITEMS.register("conure_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> FAIRYWREN_EGG = ITEMS.register("fairywren_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> PYGMY_FALCON_EGG = ITEMS.register("pygmyfalcon_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> BARN_OWL_EGG = ITEMS.register("barn_owl_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> WILD_DUCK_EGG = ITEMS.register("wild_duck_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> ROLLER_EGG = ITEMS.register("roller_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> CHICKADEE_EGG = ITEMS.register("chickadee_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> PYGMY_GOOSE_EGG = ITEMS.register("pygmy_goose_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> SWALLOW_EGG = ITEMS.register("swallow_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> IBIS_EGG = ITEMS.register("ibis_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> WOOD_DUCK_EGG = ITEMS.register("wood_duck_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> PEAFOWL_EGG = ITEMS.register("peafowl_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> SPARROW_EGG = ITEMS.register("sparrow_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> BUSHTIT_EGG = ITEMS.register("bushtit_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> EAGLEOWL_EGG = ITEMS.register("eagleowl_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> ROBIN_EGG = ITEMS.register("robin_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> LAUGHINGTHRUSH_EGG = ITEMS.register("laughingthrush_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> MAGPIE_EGG = ITEMS.register("magpie_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> GOOSE_EGG = ITEMS.register("goose_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> OSPREY_EGG = ITEMS.register("osprey_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> KINGFISHER_EGG = ITEMS.register("kingfisher_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> PELICAN_EGG = ITEMS.register("pelican_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> LAPWING_EGG = ITEMS.register("lapwing_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> SKUA_EGG = ITEMS.register("skua_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> BUNTING_EGG = ITEMS.register("bunting_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> MONAL_EGG = ITEMS.register("monal_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> TANAGER_EGG = ITEMS.register("tanager_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> FINCH_EGG = ITEMS.register("finch_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> CAPERCAILLIE_EGG = ITEMS.register("capercaillie_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> PHEASANT_EGG = ITEMS.register("pheasant_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> STORK_EGG = ITEMS.register("stork_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> WHISTLINGDUCK_EGG = ITEMS.register("whistlingduck_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> GROUND_HORNBILL_EGG = ITEMS.register("groundhornbill_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> SECRETARYBIRD_EGG = ITEMS.register("secretarybird_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> SHOEBILL_EGG = ITEMS.register("shoebill_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> STARLING_EGG = ITEMS.register("starling_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> CORMORANT_EGG = ITEMS.register("cormorant_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> PUFFIN_EGG = ITEMS.register("puffin_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> SEAGULL_EGG = ITEMS.register("seagull_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> BOOBY_EGG = ITEMS.register("booby_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> PENGUIN_EGG = ITEMS.register("bandedpenguin_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> RAIL_EGG = ITEMS.register("rail_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> AVOCET_EGG = ITEMS.register("avocet_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> CRESTED_PENGUIN_EGG = ITEMS.register("crestedpenguin_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> YELLOWEYED_PENGUIN_EGG = ITEMS.register("yelloweyedpenguin_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> BRUSHTAILED_PENGUIN_EGG = ITEMS.register("brushtailedpenguin_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> LARGE_PENGUIN_EGG = ITEMS.register("largepenguin_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> FRIGATE_EGG = ITEMS.register("frigate_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> STILT_EGG = ITEMS.register("stilt_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> LITTLEPENGUIN_EGG = ITEMS.register("littlepenguin_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> MARABOU_EGG = ITEMS.register("marabou_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> CRANE_EGG = ITEMS.register("crane_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));
    public static final RegistryObject<Item> COCKOFTHEROCK_EGG = ITEMS.register("cockoftherock_egg", () -> new EggItem(i++, (new Item.Properties()).stacksTo(1)));

    public static final RegistryObject<Item> MEALWORMS = ITEMS.register("mealworms",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(1).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> GOURAMI = ITEMS.register("raw_gourami",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(1).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> RAW_AROWANA = ITEMS.register("raw_arowana",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_AROWANA = ITEMS.register("cooked_arowana",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_KOI = ITEMS.register("raw_koi",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_KOI = ITEMS.register("roasted_koi",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_PIKE = ITEMS.register("raw_pike",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> ROASTED_PIKE = ITEMS.register("cooked_pike",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> SMALL_BIRD_MEAT = ITEMS.register("small_bird_meat",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(2).saturationMod(0.3F).meat().build())));
    public static final RegistryObject<Item> COOKED_SMALL_BIRD_MEAT = ITEMS.register("cooked_small_bird_meat",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(4).saturationMod(0.6F).meat().build())));
    public static final RegistryObject<Item> NECTAR = ITEMS.register("creatures_nectar",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(1).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> RAW_SHRIMP = ITEMS.register("raw_shrimp",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(1).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_SHRIMP = ITEMS.register("cooked_shrimp",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(3).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> LARGE_BIRD_MEAT = ITEMS.register("raw_large_wild_bird_meat",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(2).saturationMod(0.3F).meat().build())));
    public static final RegistryObject<Item> COOKED_LARGE_BIRD_MEAT = ITEMS.register("roasted_large_wild_bird_meat",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(8).saturationMod(0.6F).meat().build())));
    public static final RegistryObject<Item> RAW_TROUT = ITEMS.register("item_trout",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_TROUT = ITEMS.register("cooked_trout",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(7).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_RED_SNAPPER = ITEMS.register("raw_red_snapper",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_RED_SNAPPER = ITEMS.register("cooked_red_snapper",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(7).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_ARAPAIMA = ITEMS.register("raw_arapaima",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(3).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_ARAPAIMA = ITEMS.register("cooked_arapaima",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(10).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_PIRANHA = ITEMS.register("raw_piranha",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(3).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_PIRANHA = ITEMS.register("cooked_piranha",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_TAMBAQUI = ITEMS.register("raw_tambaqui",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(3).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_TAMBAQUI = ITEMS.register("cooked_tambaqui",() -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_SWORDFISH = ITEMS.register("raw_swordfish_steak", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_SWORDFISH = ITEMS.register("cooked_swordfish_steak", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_SQUID = ITEMS.register("raw_squid", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> CALAMARI = ITEMS.register("calamari", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RED_SNAPPER_SASHIMI = ITEMS.register("red_snapper_sashimi", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.4F).build())));
    public static final RegistryObject<Item> TROUT_SASHIMI = ITEMS.register("trout_sashimi", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.4F).build())));
    public static final RegistryObject<Item> SWORDFISH_SASHIMI = ITEMS.register("swordfish_sashimi", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.5F).build())));
    public static final RegistryObject<Item> SQUID_SASHIMI = ITEMS.register("squid_sashimi", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(5).saturationMod(0.4F).build())));
    public static final RegistryObject<Item> RAW_EDIBLECRAB = ITEMS.register("ediblecrab", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_EDIBLECRAB = ITEMS.register("cooked_ediblecrab", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_BLUECRAB = ITEMS.register("raw_bluecrab", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_BLUECRAB = ITEMS.register("cooked_bluecrab", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_DUNGENESSCRAB = ITEMS.register("raw_dungenesscrab", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_DUNGENESSCRAB = ITEMS.register("cooked_dungenesscrab", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_LUNGFISH = ITEMS.register("raw_lungfish", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_LUNGFISH = ITEMS.register("cooked_lungfish", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_PARROTFISH = ITEMS.register("raw_parrotfish", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_PARROTFISH = ITEMS.register("cooked_parrotfish", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(7).saturationMod(0.6F).build())));
    public static final RegistryObject<Item> RAW_ROCKCRAB = ITEMS.register("raw_rockcrab", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.3F).build())));
    public static final RegistryObject<Item> COOKED_ROCKCRAB = ITEMS.register("cooked_rockcrab", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).build())));

    public static final RegistryObject<ForgeSpawnEggItem> KOI_SPAWN_EGG = ITEMS.register("koi_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.KOI, 16731716, 16777215));
    public static final RegistryObject<ForgeSpawnEggItem> LOVEBIRD_SPAWN_EGG = ITEMS.register("lovebird_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.LOVEBIRD, 16749375, 16765696));
    public static final RegistryObject<ForgeSpawnEggItem> SPOONBILL_SPAWN_EGG = ITEMS.register("spoonbill_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SPOONBILL, 16490917, 16583198));
    public static final RegistryObject<ForgeSpawnEggItem> KAKAPO_SPAWN_EGG = ITEMS.register("kakapo_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.KAKAPO,9607980, 12299667));
    public static final RegistryObject<ForgeSpawnEggItem> DOTTYBACK_SPAWN_EGG = ITEMS.register("dottyback_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.DOTTYBACK, 16740608, 6058495));
    public static final RegistryObject<ForgeSpawnEggItem> PIKE_SPAWN_EGG = ITEMS.register("pike_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.PIKE, 10973747, 16777215));
    public static final RegistryObject<ForgeSpawnEggItem> GUPPY_SPAWN_EGG = ITEMS.register("guppy_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.GUPPY, 8578898, 8579010));
    public static final RegistryObject<ForgeSpawnEggItem> MANDARIN_DUCK_SPAWN_EGG = ITEMS.register("mandarin_duck_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.MANDARIN_DUCK, 11798553, 16640178));
    public static final RegistryObject<ForgeSpawnEggItem> AROWANA_SPAWN_EGG = ITEMS.register("arowana_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.AROWANA, 16771881, 16758578));
    public static final RegistryObject<ForgeSpawnEggItem> RAVEN_SPAWN_EGG = ITEMS.register("raven_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.RAVEN, 9536, 4152450));
    public static final RegistryObject<ForgeSpawnEggItem> SHRIMP_SPAWN_EGG = ITEMS.register("shrimp_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SHRIMP, 16583198, 16490917));
    public static final RegistryObject<ForgeSpawnEggItem> DOVE_SPAWN_EGG = ITEMS.register("dove_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.DOVE, 14935271, 15395538));
    public static final RegistryObject<ForgeSpawnEggItem> RED_KITE_SPAWN_EGG = ITEMS.register("red_kite_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.RED_KITE, 13651220, 4152450));
    public static final RegistryObject<ForgeSpawnEggItem> GOLDEN_EAGLE_SPAWN_EGG = ITEMS.register("golden_eagle_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.GOLDEN_EAGLE, 4525319, 10125934));
    public static final RegistryObject<ForgeSpawnEggItem> STELLERS_SEA_EAGLE_SPAWN_EGG = ITEMS.register("stellers_sea_eagle_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SEA_EAGLE, 5322812, 16515071));
    public static final RegistryObject<ForgeSpawnEggItem> GYRFALCON_SPAWN_EGG = ITEMS.register("gyrfalcon_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.GYRFALCON, 16515071, 9536));
    public static final RegistryObject<ForgeSpawnEggItem> LORIKEET_SPAWN_EGG = ITEMS.register("lorikeet_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.LORIKEET, 3093151, 16718368));
    public static final RegistryObject<ForgeSpawnEggItem> CONURE_SPAWN_EGG = ITEMS.register("conure_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.CONURE, 16170000, 2182420));
    public static final RegistryObject<ForgeSpawnEggItem> FAIRYWREN_SPAWN_EGG = ITEMS.register("fairywren_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.FAIRYWREN, 1650103, 41));
    public static final RegistryObject<ForgeSpawnEggItem> GHOST_CRAB_SPAWN_EGG = ITEMS.register("ghostcrab_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.GHOST_CRAB, 13545576, 16777215));
    public static final RegistryObject<ForgeSpawnEggItem> GOURAMI_SPAWN_EGG = ITEMS.register("gourami_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.GOURAMI, 4152450, 16777215));
    public static final RegistryObject<ForgeSpawnEggItem> PYGMY_FALCON_SPAWN_EGG = ITEMS.register("pygmy_falcon_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.PYGMY_FALCON, 8097951, 15724012));
    public static final RegistryObject<ForgeSpawnEggItem> BARN_OWL_SPAWN_EGG = ITEMS.register("barn_owl_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.BARN_OWL, 16777215, 11897942));
    public static final RegistryObject<ForgeSpawnEggItem> WILD_DUCK_SPAWN_EGG = ITEMS.register("wild_duck_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.WILD_DUCK, 15702874, 7901340));
    public static final RegistryObject<ForgeSpawnEggItem> ROLLER_SPAWN_EGG = ITEMS.register("roller_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.ROLLER, 1414724, 13192647));
    public static final RegistryObject<ForgeSpawnEggItem> GOLDFISH_SPAWN_EGG = ITEMS.register("goldfish_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.GOLDFISH, 14501642, 14318603));
    public static final RegistryObject<ForgeSpawnEggItem> RANCHU_SPAWN_EGG = ITEMS.register("ranchu_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.RANCHU, 14501642, 11));
    public static final RegistryObject<ForgeSpawnEggItem> CHICKADEE_SPAWN_EGG = ITEMS.register("chickadee_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.CHICKADEE, 13879499, 11));
    public static final RegistryObject<ForgeSpawnEggItem> PYGMY_GOOSE_SPAWN_EGG = ITEMS.register("pygmy_goose_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.PYGMY_GOOSE, 2772553, 15964498));
    public static final RegistryObject<ForgeSpawnEggItem> FIRE_GOBY_SPAWN_EGG = ITEMS.register("fire_goby_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.FIRE_GOBY, 14080426, 15964498));
    public static final RegistryObject<ForgeSpawnEggItem> BLUE_TANG_SPAWN_EGG = ITEMS.register("blue_tang_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.BLUE_TANG, 3895524, 722696));
    public static final RegistryObject<ForgeSpawnEggItem> FLAME_ANGELFISH_SPAWN_EGG = ITEMS.register("flame_angelfish_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.FLAME_ANGELFISH, 16396073, 16611846));
    public static final RegistryObject<ForgeSpawnEggItem> TROUT_SPAWN_EGG = ITEMS.register("trout_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.TROUT, 9861465, 11822456));
    public static final RegistryObject<ForgeSpawnEggItem> SWALLOW_SPAWN_EGG = ITEMS.register("swallow_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SWALLOW, 6588890, 11953480));
    public static final RegistryObject<ForgeSpawnEggItem> FIDDLER_CRAB_SPAWN_EGG = ITEMS.register("fiddler_crab_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.FIDDLER_CRAB, 526085, 9297374));
    public static final RegistryObject<ForgeSpawnEggItem> IBIS_SPAWN_EGG = ITEMS.register("ibis_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.IBIS, 13178131, 13847612));
    public static final RegistryObject<ForgeSpawnEggItem> RED_SNAPPER_SPAWN_EGG = ITEMS.register("red_snapper_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.RED_SNAPPER, 15320002, 13979723));
    public static final RegistryObject<ForgeSpawnEggItem> WOOD_DUCK_SPAWN_EGG = ITEMS.register("wood_duck_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.WOOD_DUCK, 2967328, 7548455));
    public static final RegistryObject<ForgeSpawnEggItem> PEAFOWL_SPAWN_EGG = ITEMS.register("peafowl_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.PEAFOWL, 32466, 2450496));
    public static final RegistryObject<ForgeSpawnEggItem> SPARROW_SPAWN_EGG = ITEMS.register("sparrow_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SPARROW, 9004362, 13743005));
    public static final RegistryObject<ForgeSpawnEggItem> BUSHTIT_SPAWN_EGG = ITEMS.register("bushtit_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.BUSHTIT, 16382707, 9004362));
    public static final RegistryObject<ForgeSpawnEggItem> EAGLEOWL_SPAWN_EGG = ITEMS.register("eagleowl_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.EAGLEOWL, 13608552, 4798501));
    public static final RegistryObject<ForgeSpawnEggItem> ROBIN_SPAWN_EGG = ITEMS.register("robin_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.ROBIN, 9600343, 13723915));
    public static final RegistryObject<ForgeSpawnEggItem> LAUGHINGTHRUSH_SPAWN_EGG = ITEMS.register("laughingthrush_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.LAUGHINGTHRUSH, 8873290, 15720079));
    public static final RegistryObject<ForgeSpawnEggItem> MAGPIE_SPAWN_EGG = ITEMS.register("magpie_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.MAGPIE, 1908259, 4480395));
    public static final RegistryObject<ForgeSpawnEggItem> GOOSE_SPAWN_EGG = ITEMS.register("goose_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.GOOSE, 7888451, 525056));
    public static final RegistryObject<ForgeSpawnEggItem> OSPREY_SPAWN_EGG = ITEMS.register("osprey_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.OSPREY, 14869470, 4732721));
    public static final RegistryObject<ForgeSpawnEggItem> KINGFISHER_SPAWN_EGG = ITEMS.register("kingfisher_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.KINGFISHER, 29897, 13722630));
    public static final RegistryObject<ForgeSpawnEggItem> PELICAN_SPAWN_EGG = ITEMS.register("pelican_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.PELICAN, 15787740, 14585696));
    public static final RegistryObject<ForgeSpawnEggItem> LAPWING_SPAWN_EGG = ITEMS.register("lapwing_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.LAPWING, 1921595, 528151));
    public static final RegistryObject<ForgeSpawnEggItem> SKUA_SPAWN_EGG = ITEMS.register("skua_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SKUA, 6182224, 4011831));
    public static final RegistryObject<ForgeSpawnEggItem> BUNTING_SPAWN_EGG = ITEMS.register("bunting_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.BUNTING, 4138700, 13379110));
    public static final RegistryObject<ForgeSpawnEggItem> MONAL_SPAWN_EGG = ITEMS.register("monal_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.MONAL, 1447449, 5493427));
    public static final RegistryObject<ForgeSpawnEggItem> TANAGER_SPAWN_EGG = ITEMS.register("tanager_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.TANAGER, 1973286, 11066120));
    public static final RegistryObject<ForgeSpawnEggItem> FINCH_SPAWN_EGG = ITEMS.register("finch_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.FINCH, 10590093, 11557643));
    public static final RegistryObject<ForgeSpawnEggItem> VAMPIRE_CRAB_SPAWN_EGG = ITEMS.register("vampirecrab_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.VAMPIRECRAB, 1579024, 7024730));
    public static final RegistryObject<ForgeSpawnEggItem> TARANTULA_SPAWN_EGG = ITEMS.register("tarantula_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.TARANTULA, 657678, 11427379));
    public static final RegistryObject<ForgeSpawnEggItem> CAPERCAILLIE_SPAWN_EGG = ITEMS.register("capercaillie_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.CAPERCAILLIE, 3685214, 16316664));
    public static final RegistryObject<ForgeSpawnEggItem> TIGERBARB_SPAWN_EGG = ITEMS.register("tigerbarb_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.TIGERBARB, 10718525, 1250617));
    public static final RegistryObject<ForgeSpawnEggItem> PHEASANT_SPAWN_EGG = ITEMS.register("pheasant_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.PHEASANT, 16306176, 11013921));
    public static final RegistryObject<ForgeSpawnEggItem> ARAPAIMA_SPAWN_EGG = ITEMS.register("arapaima_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.ARAPAIMA, 4739385, 11620159));
    public static final RegistryObject<ForgeSpawnEggItem> PIRANHA_SPAWN_EGG = ITEMS.register("piranha_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.PIRANHA, 8880781, 12006170));
    public static final RegistryObject<ForgeSpawnEggItem> STORK_SPAWN_EGG = ITEMS.register("stork_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.STORK, 16777215, 1710622));
    public static final RegistryObject<ForgeSpawnEggItem> WHISTLINGDUCK_SPAWN_EGG = ITEMS.register("whistlingduck_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.WHISTLING_DUCK, 13741962, 8402969));
    public static final RegistryObject<ForgeSpawnEggItem> GROUND_HORNBILL_SPAWN_EGG = ITEMS.register("groundhornbill_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.GROUND_HORNBILL, 1842204, 12599604));
    public static final RegistryObject<ForgeSpawnEggItem> SECRETARYBIRD_SPAWN_EGG = ITEMS.register("secretarybird_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SECRETARYBIRD, 10394523, 15555084));
    public static final RegistryObject<ForgeSpawnEggItem> SHOEBILL_SPAWN_EGG = ITEMS.register("shoebill_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SHOEBILL, 10267065, 5071228));
    public static final RegistryObject<ForgeSpawnEggItem> STARLING_SPAWN_EGG = ITEMS.register("starling_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.STARLING, 1385047, 14854402));
    public static final RegistryObject<ForgeSpawnEggItem> TAMBAQUI_SPAWN_EGG = ITEMS.register("tambaqui_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.TAMBAQUI, 6709327, 986895));
    public static final RegistryObject<ForgeSpawnEggItem> ELEPHANTNOSE_SPAWN_EGG = ITEMS.register("elephantnose_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.ELEPHANTNOSE, 9665641, 4274747));
    public static final RegistryObject<ForgeSpawnEggItem> CORMORANT_SPAWN_EGG = ITEMS.register("cormorant_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.CORMORANT, 3289400, 6314590));
    public static final RegistryObject<ForgeSpawnEggItem> STINGRAY_SPAWN_EGG = ITEMS.register("stingray_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.STINGRAY, 6440497, 9206887));
    public static final RegistryObject<ForgeSpawnEggItem> PUFFIN_SPAWN_EGG = ITEMS.register("puffin_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.PUFFIN, 9536, 16777215));
    public static final RegistryObject<ForgeSpawnEggItem> SAWFISH_SPAWN_EGG = ITEMS.register("sawfish_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SAWFISH, 4670516, 3025693));
    public static final RegistryObject<ForgeSpawnEggItem> SEAGULL_SPAWN_EGG = ITEMS.register("seagull_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SEAGULL, 16777215, 9536));
    public static final RegistryObject<ForgeSpawnEggItem> SWORDFISH_SPAWN_EGG = ITEMS.register("swordfish_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SWORDFISH, 139, 9536));
    public static final RegistryObject<ForgeSpawnEggItem> BOOBY_SPAWN_EGG = ITEMS.register("booby_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.BOOBY, 12887172, 11393254));
    public static final RegistryObject<ForgeSpawnEggItem> SQUID_SPAWN_EGG = ITEMS.register("squid_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SQUID, 13068118, 8264982));
    public static final RegistryObject<ForgeSpawnEggItem> LOOKDOWN_SPAWN_EGG = ITEMS.register("lookdown_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.LOOKDOWN, 11648969, 10328354));
    public static final RegistryObject<ForgeSpawnEggItem> BANDED_PENGUIN_SPAWN_EGG = ITEMS.register("bandedpenguin_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.BANDED_PENGUIN, 4669245, 15855341));
    public static final RegistryObject<ForgeSpawnEggItem> MANTIS_SHRIMP_SPAWN_EGG = ITEMS.register("mantisshrimp_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.MANTIS_SHRIMP, 3646286, 13114396));
    public static final RegistryObject<ForgeSpawnEggItem> RAIL_SPAWN_EGG = ITEMS.register("rail_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.RAIL, 1579032, 8220520));
    public static final RegistryObject<ForgeSpawnEggItem> BARRACUDA_SPAWN_EGG = ITEMS.register("barracuda_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.BARRACUDA, 5858925, 65793));
    public static final RegistryObject<ForgeSpawnEggItem> AVOCET_SPAWN_EGG = ITEMS.register("avocet_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.AVOCET, 10571800, 15921906));
    public static final RegistryObject<ForgeSpawnEggItem> SEADRAGON_SPAWN_EGG = ITEMS.register("seadragon_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.SEADRAGON, 14267396, 9547602));
    public static final RegistryObject<ForgeSpawnEggItem> TRUMPETFISH_SPAWN_EGG = ITEMS.register("trumpetfish_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.TRUMPETFISH, 9211012, 12367651));
    public static final RegistryObject<ForgeSpawnEggItem> CRESTED_PENGUIN_SPAWN_EGG = ITEMS.register("crestedpenguin_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.CRESTED_PENGUIN, 789516, 15526527));
    public static final RegistryObject<ForgeSpawnEggItem> PARROTFISH_SPAWN_EGG = ITEMS.register("parrotfish_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.PARROTFISH, 5560761, 15227534));
    public static final RegistryObject<ForgeSpawnEggItem> YELLOW_EYED_PENGUIN_SPAWN_EGG = ITEMS.register("yelloweyedpenguin_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.YELLOW_EYED_PENGUIN, 2629146, 15654305));
    public static final RegistryObject<ForgeSpawnEggItem> BRUSH_TAILED_PENGUIN_SPAWN_EGG = ITEMS.register("brushtailedpenguin_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.BRUSH_TAILED_PENGUIN, 0, 16777215));
    public static final RegistryObject<ForgeSpawnEggItem> LARGE_PENGUIN_SPAWN_EGG = ITEMS.register("largepenguin_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.LARGE_PENGUIN, 4606031, 16381150));
    public static final RegistryObject<ForgeSpawnEggItem> FRIGATE_SPAWN_EGG = ITEMS.register("frigate_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.FRIGATE, 1842465, 15078180));
    public static final RegistryObject<ForgeSpawnEggItem> CLOWNFISH_SPAWN_EGG = ITEMS.register("clownfish_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.CLOWNFISH, 14967298, 16777215));
    public static final RegistryObject<ForgeSpawnEggItem> STILT_SPAWN_EGG = ITEMS.register("stilt_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.STILT, 16777215, 986895));
    public static final RegistryObject<ForgeSpawnEggItem> LUNGFISH_SPAWN_EGG = ITEMS.register("lungfish_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.LUNGFISH, 5065792, 3552813));
    public static final RegistryObject<ForgeSpawnEggItem> LITTLE_PENGUIN_SPAWN_EGG = ITEMS.register("littlepenguin_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.LITTLE_PENGUIN, 1855087, 16382200));
    public static final RegistryObject<ForgeSpawnEggItem> EDIBLE_CRAB_SPAWN_EGG = ITEMS.register("ediblecrab_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.EDIBLE_CRAB, 5646361, 460551));
    public static final RegistryObject<ForgeSpawnEggItem> MARABOU_SPAWN_EGG = ITEMS.register("marabou_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.MARABOU, 6318976, 13866302));
    public static final RegistryObject<ForgeSpawnEggItem> CRANE_SPAWN_EGG = ITEMS.register("crane_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.CRANE, 16053233, 12208446));
    public static final RegistryObject<ForgeSpawnEggItem> COCK_OF_THE_ROCK_SPAWN_EGG = ITEMS.register("cockoftherock_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.COCK_OF_THE_ROCK, 16734976, 1183759));
    public static final RegistryObject<ForgeSpawnEggItem> TETRA_SPAWN_EGG = ITEMS.register("tetra_spawn_egg", () -> new ModSpawnEggVariants(CreaturesEntities.TETRA, 12697482, 11801347));

    public static final RegistryObject<CreativeModeTab> FRIKINZIS_TAB = TABS.register("creaturesitems", () -> CreativeModeTab.builder()
            .title(Component.translatable("itemGroup." + Creatures.MODID + ".creaturesitems"))
            .icon(() -> new ItemStack(CreaturesItems.RAW_KOI.get()))
            .displayItems((enabledFeatures, entries) -> {
                entries.accept(CreaturesItems.KOI_BUCKET.get());
                entries.accept(CreaturesItems.DOTTYBACK_BUCKET.get());
                entries.accept(CreaturesItems.PIKE_BUCKET.get());
                entries.accept(CreaturesItems.GUPPY_BUCKET.get());
                entries.accept(CreaturesItems.AROWANA_BUCKET.get());
                entries.accept(CreaturesItems.SHRIMP_BUCKET.get());
                entries.accept(CreaturesItems.GOURAMI_BUCKET.get());
                entries.accept(CreaturesItems.GOLDFISH_BUCKET.get());
                entries.accept(CreaturesItems.RANCHU_BUCKET.get());
                entries.accept(CreaturesItems.FIRE_GOBY_BUCKET.get());
                entries.accept(CreaturesItems.BLUE_TANG_BUCKET.get());
                entries.accept(CreaturesItems.TROUT_BUCKET.get());
                entries.accept(CreaturesItems.FLAME_ANGELFISH_BUCKET.get());
                entries.accept(CreaturesItems.RED_SNAPPER_BUCKET.get());
                entries.accept(CreaturesItems.TIGER_BARB_BUCKET.get());
                entries.accept(CreaturesItems.ARAPAIMA_BUCKET.get());
                entries.accept(CreaturesItems.PIRANHA_BUCKET.get());
                entries.accept(CreaturesItems.TAMBAQUI_BUCKET.get());
                entries.accept(CreaturesItems.ELEPHANTNOSE_BUCKET.get());
                entries.accept(CreaturesItems.CLOWNFISH_BUCKET.get());
                entries.accept(CreaturesItems.LOOKDOWN_BUCKET.get());
                entries.accept(CreaturesItems.SEADRAGON_BUCKET.get());
                entries.accept(CreaturesItems.MANTIS_SHRIMP_BUCKET.get());
                entries.accept(CreaturesItems.TRUMPETFISH_BUCKET.get());
                entries.accept(CreaturesItems.PARROTFISH_BUCKET.get());
                entries.accept(CreaturesItems.TETRA_BUCKET.get());

                entries.accept(CreaturesItems.GUPPY_TAIL.get());
                entries.accept(CreaturesItems.GOLDFISH.get());
                entries.accept(CreaturesItems.CRAB_PINCERS.get());
                entries.accept(CreaturesItems.DUCK_FEATHER.get());
                entries.accept(CreaturesItems.BIRD_OF_PREY_FEATHER.get());
                entries.accept(CreaturesItems.RAVEN_FEATHER.get());
                entries.accept(CreaturesItems.PARROT_FEATHER.get());
                entries.accept(CreaturesItems.FF_GUIDE.get());
                entries.accept(CreaturesItems.FISHING_BIN.get());
                entries.accept(CreaturesItems.PEAFOWL_FEATHER.get());
                entries.accept(CreaturesItems.BIRD_CARRIER.get());
                entries.accept(CreaturesItems.CRITTER_KEEPER.get());
                entries.accept(CreaturesItems.FISH_FOOD.get());
                entries.accept(CreaturesItems.ALGAE_WAFER.get());
                entries.accept(CreaturesItems.FISHING_NET.get());
                entries.accept(CreaturesItems.FF_GUIDE.get());
                entries.accept(CreaturesItems.MEALWORMS.get());
                entries.accept(CreaturesItems.GOURAMI.get());
                entries.accept(CreaturesItems.RAW_AROWANA.get());
                entries.accept(CreaturesItems.COOKED_AROWANA.get());
                entries.accept(CreaturesItems.COOKED_KOI.get());
                entries.accept(CreaturesItems.RAW_KOI.get());
                entries.accept(CreaturesItems.RAW_PIKE.get());
                entries.accept(CreaturesItems.ROASTED_PIKE.get());
                entries.accept(CreaturesItems.SMALL_BIRD_MEAT.get());
                entries.accept(CreaturesItems.COOKED_SMALL_BIRD_MEAT.get());
                entries.accept(CreaturesItems.NECTAR.get());
                entries.accept(CreaturesItems.RAW_SHRIMP.get());
                entries.accept(CreaturesItems.COOKED_SHRIMP.get());
                entries.accept(CreaturesItems.LARGE_BIRD_MEAT.get());
                entries.accept(CreaturesItems.COOKED_LARGE_BIRD_MEAT.get());
                entries.accept(CreaturesItems.RAW_TROUT.get());
                entries.accept(CreaturesItems.COOKED_TROUT.get());
                entries.accept(CreaturesItems.RAW_RED_SNAPPER.get());
                entries.accept(CreaturesItems.COOKED_RED_SNAPPER.get());
                entries.accept(CreaturesItems.RAW_ARAPAIMA.get());
                entries.accept(CreaturesItems.COOKED_ARAPAIMA.get());
                entries.accept(CreaturesItems.RAW_PIRANHA.get());
                entries.accept(CreaturesItems.COOKED_PIRANHA.get());
                entries.accept(CreaturesItems.RAW_TAMBAQUI.get());
                entries.accept(CreaturesItems.COOKED_TAMBAQUI.get());
                entries.accept(CreaturesItems.RAW_SWORDFISH.get());
                entries.accept(CreaturesItems.COOKED_SWORDFISH.get());
                entries.accept(CreaturesItems.RAW_SQUID.get());
                entries.accept(CreaturesItems.CALAMARI.get());
                entries.accept(CreaturesItems.RED_SNAPPER_SASHIMI.get());
                entries.accept(CreaturesItems.TROUT_SASHIMI.get());
                entries.accept(CreaturesItems.SWORDFISH_SASHIMI.get());
                entries.accept(CreaturesItems.SQUID_SASHIMI.get());
                entries.accept(CreaturesItems.RAW_EDIBLECRAB.get());
                entries.accept(CreaturesItems.COOKED_EDIBLECRAB.get());
                entries.accept(CreaturesItems.RAW_BLUECRAB.get());
                entries.accept(CreaturesItems.COOKED_BLUECRAB.get());
                entries.accept(CreaturesItems.RAW_DUNGENESSCRAB.get());
                entries.accept(CreaturesItems.COOKED_DUNGENESSCRAB.get());
                entries.accept(CreaturesItems.RAW_LUNGFISH.get());
                entries.accept(CreaturesItems.COOKED_LUNGFISH.get());
                entries.accept(CreaturesItems.RAW_PARROTFISH.get());
                entries.accept(CreaturesItems.COOKED_PARROTFISH.get());
                entries.accept(CreaturesItems.RAW_ROCKCRAB.get());
                entries.accept(CreaturesItems.COOKED_ROCKCRAB.get());

                entries.accept(CreaturesItems.LOVEBIRD_EGG.get());
                entries.accept(CreaturesItems.SPOONBILL_EGG.get());
                entries.accept(CreaturesItems.KAKAPO_EGG.get());
                entries.accept(CreaturesItems.MANDARIN_DUCK_EGG.get());
                entries.accept(CreaturesItems.RAVEN_EGG.get());
                entries.accept(CreaturesItems.DOVE_EGG.get());
                entries.accept(CreaturesItems.RED_KITE_EGG.get());
                entries.accept(CreaturesItems.GOLDEN_EAGLE_EGG.get());
                entries.accept(CreaturesItems.STELLERS_SEA_EAGLE_EGG.get());
                entries.accept(CreaturesItems.GYRFALCON_EGG.get());
                entries.accept(CreaturesItems.LORIKEET_EGG.get());
                entries.accept(CreaturesItems.CONURE_EGG.get());
                entries.accept(CreaturesItems.FAIRYWREN_EGG.get());
                entries.accept(CreaturesItems.PYGMY_FALCON_EGG.get());
                entries.accept(CreaturesItems.BARN_OWL_EGG.get());
                entries.accept(CreaturesItems.WILD_DUCK_EGG.get());
                entries.accept(CreaturesItems.ROLLER_EGG.get());
                entries.accept(CreaturesItems.CHICKADEE_EGG.get());
                entries.accept(CreaturesItems.PYGMY_GOOSE_EGG.get());
                entries.accept(CreaturesItems.SWALLOW_EGG.get());
                entries.accept(CreaturesItems.IBIS_EGG.get());
                entries.accept(CreaturesItems.WOOD_DUCK_EGG.get());
                entries.accept(CreaturesItems.PEAFOWL_EGG.get());
                entries.accept(CreaturesItems.SPARROW_EGG.get());
                entries.accept(CreaturesItems.BUSHTIT_EGG.get());
                entries.accept(CreaturesItems.EAGLEOWL_EGG.get());
                entries.accept(CreaturesItems.ROBIN_EGG.get());
                entries.accept(CreaturesItems.LAUGHINGTHRUSH_EGG.get());
                entries.accept(CreaturesItems.MAGPIE_EGG.get());
                entries.accept(CreaturesItems.GOOSE_EGG.get());
                entries.accept(CreaturesItems.OSPREY_EGG.get());
                entries.accept(CreaturesItems.KINGFISHER_EGG.get());
                entries.accept(CreaturesItems.PELICAN_EGG.get());
                entries.accept(CreaturesItems.LAPWING_EGG.get());
                entries.accept(CreaturesItems.SKUA_EGG.get());
                entries.accept(CreaturesItems.BUNTING_EGG.get());
                entries.accept(CreaturesItems.MONAL_EGG.get());
                entries.accept(CreaturesItems.TANAGER_EGG.get());
                entries.accept(CreaturesItems.FINCH_EGG.get());
                entries.accept(CreaturesItems.CAPERCAILLIE_EGG.get());
                entries.accept(CreaturesItems.PHEASANT_EGG.get());
                entries.accept(CreaturesItems.STORK_EGG.get());
                entries.accept(CreaturesItems.WHISTLINGDUCK_EGG.get());
                entries.accept(CreaturesItems.GROUND_HORNBILL_EGG.get());
                entries.accept(CreaturesItems.SECRETARYBIRD_EGG.get());
                entries.accept(CreaturesItems.SHOEBILL_EGG.get());
                entries.accept(CreaturesItems.STARLING_EGG.get());
                entries.accept(CreaturesItems.CORMORANT_EGG.get());
                entries.accept(CreaturesItems.PUFFIN_EGG.get());
                entries.accept(CreaturesItems.SEAGULL_EGG.get());
                entries.accept(CreaturesItems.BOOBY_EGG.get());
                entries.accept(CreaturesItems.PENGUIN_EGG.get());
                entries.accept(CreaturesItems.RAIL_EGG.get());
                entries.accept(CreaturesItems.AVOCET_EGG.get());
                entries.accept(CreaturesItems.CRESTED_PENGUIN_EGG.get());
                entries.accept(CreaturesItems.YELLOWEYED_PENGUIN_EGG.get());
                entries.accept(CreaturesItems.BRUSHTAILED_PENGUIN_EGG.get());
                entries.accept(CreaturesItems.LARGE_PENGUIN_EGG.get());
                entries.accept(CreaturesItems.FRIGATE_EGG.get());
                entries.accept(CreaturesItems.STILT_EGG.get());
                entries.accept(CreaturesItems.LITTLEPENGUIN_EGG.get());
                entries.accept(CreaturesItems.MARABOU_EGG.get());
                entries.accept(CreaturesItems.CRANE_EGG.get());
                entries.accept(CreaturesItems.COCKOFTHEROCK_EGG.get());

                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY1.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY2.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY3.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY4.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY5.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY6.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY7.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY8.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY9.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY10.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY11.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY12.get()));
                entries.accept(Item.BY_BLOCK.get(CreaturesBlocks.TOY13.get()));
                //SPAWN EGGS
                entries.accept(CreaturesItems.KOI_SPAWN_EGG.get());
                entries.accept(CreaturesItems.LOVEBIRD_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SPOONBILL_SPAWN_EGG.get());
                entries.accept(CreaturesItems.KAKAPO_SPAWN_EGG.get());
                entries.accept(CreaturesItems.DOTTYBACK_SPAWN_EGG.get());
                entries.accept(CreaturesItems.PIKE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.GUPPY_SPAWN_EGG.get());
                entries.accept(CreaturesItems.MANDARIN_DUCK_SPAWN_EGG.get());
                entries.accept(CreaturesItems.AROWANA_SPAWN_EGG.get());
                entries.accept(CreaturesItems.RAVEN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SHRIMP_SPAWN_EGG.get());
                entries.accept(CreaturesItems.DOVE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.RED_KITE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.GOLDEN_EAGLE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.STELLERS_SEA_EAGLE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.GYRFALCON_SPAWN_EGG.get());
                entries.accept(CreaturesItems.LORIKEET_SPAWN_EGG.get());
                entries.accept(CreaturesItems.CONURE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.FAIRYWREN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.GHOST_CRAB_SPAWN_EGG.get());
                entries.accept(CreaturesItems.GOURAMI_SPAWN_EGG.get());
                entries.accept(CreaturesItems.PYGMY_FALCON_SPAWN_EGG.get());
                entries.accept(CreaturesItems.BARN_OWL_SPAWN_EGG.get());
                entries.accept(CreaturesItems.WILD_DUCK_SPAWN_EGG.get());
                entries.accept(CreaturesItems.ROLLER_SPAWN_EGG.get());
                entries.accept(CreaturesItems.GOLDFISH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.RANCHU_SPAWN_EGG.get());
                entries.accept(CreaturesItems.CHICKADEE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.PYGMY_GOOSE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.FIRE_GOBY_SPAWN_EGG.get());
                entries.accept(CreaturesItems.BLUE_TANG_SPAWN_EGG.get());
                entries.accept(CreaturesItems.FLAME_ANGELFISH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.TROUT_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SWALLOW_SPAWN_EGG.get());
                entries.accept(CreaturesItems.FIDDLER_CRAB_SPAWN_EGG.get());
                entries.accept(CreaturesItems.IBIS_SPAWN_EGG.get());
                entries.accept(CreaturesItems.RED_SNAPPER_SPAWN_EGG.get());
                entries.accept(CreaturesItems.WOOD_DUCK_SPAWN_EGG.get());
                entries.accept(CreaturesItems.PEAFOWL_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SPARROW_SPAWN_EGG.get());
                entries.accept(CreaturesItems.BUSHTIT_SPAWN_EGG.get());
                entries.accept(CreaturesItems.EAGLEOWL_SPAWN_EGG.get());
                entries.accept(CreaturesItems.ROBIN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.LAUGHINGTHRUSH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.MAGPIE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.GOOSE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.OSPREY_SPAWN_EGG.get());
                entries.accept(CreaturesItems.KINGFISHER_SPAWN_EGG.get());
                entries.accept(CreaturesItems.PELICAN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.LAPWING_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SKUA_SPAWN_EGG.get());
                entries.accept(CreaturesItems.BUNTING_SPAWN_EGG.get());
                entries.accept(CreaturesItems.MONAL_SPAWN_EGG.get());
                entries.accept(CreaturesItems.TANAGER_SPAWN_EGG.get());
                entries.accept(CreaturesItems.FINCH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.VAMPIRE_CRAB_SPAWN_EGG.get());
                entries.accept(CreaturesItems.TARANTULA_SPAWN_EGG.get());
                entries.accept(CreaturesItems.CAPERCAILLIE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.TIGERBARB_SPAWN_EGG.get());
                entries.accept(CreaturesItems.PHEASANT_SPAWN_EGG.get());
                entries.accept(CreaturesItems.ARAPAIMA_SPAWN_EGG.get());
                entries.accept(CreaturesItems.PIRANHA_SPAWN_EGG.get());
                entries.accept(CreaturesItems.STORK_SPAWN_EGG.get());
                entries.accept(CreaturesItems.WHISTLINGDUCK_SPAWN_EGG.get());
                entries.accept(CreaturesItems.GROUND_HORNBILL_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SECRETARYBIRD_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SHOEBILL_SPAWN_EGG.get());
                entries.accept(CreaturesItems.STARLING_SPAWN_EGG.get());
                entries.accept(CreaturesItems.TAMBAQUI_SPAWN_EGG.get());
                entries.accept(CreaturesItems.ELEPHANTNOSE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.CORMORANT_SPAWN_EGG.get());
                entries.accept(CreaturesItems.STINGRAY_SPAWN_EGG.get());
                entries.accept(CreaturesItems.PUFFIN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SAWFISH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SEAGULL_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SWORDFISH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.BOOBY_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SQUID_SPAWN_EGG.get());
                entries.accept(CreaturesItems.LOOKDOWN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.BANDED_PENGUIN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.MANTIS_SHRIMP_SPAWN_EGG.get());
                entries.accept(CreaturesItems.RAIL_SPAWN_EGG.get());
                entries.accept(CreaturesItems.BARRACUDA_SPAWN_EGG.get());
                entries.accept(CreaturesItems.AVOCET_SPAWN_EGG.get());
                entries.accept(CreaturesItems.SEADRAGON_SPAWN_EGG.get());
                entries.accept(CreaturesItems.TRUMPETFISH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.CRESTED_PENGUIN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.PARROTFISH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.YELLOW_EYED_PENGUIN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.BRUSH_TAILED_PENGUIN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.LARGE_PENGUIN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.FRIGATE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.CLOWNFISH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.STILT_SPAWN_EGG.get());
                entries.accept(CreaturesItems.LUNGFISH_SPAWN_EGG.get());
                entries.accept(CreaturesItems.LITTLE_PENGUIN_SPAWN_EGG.get());
                entries.accept(CreaturesItems.EDIBLE_CRAB_SPAWN_EGG.get());
                entries.accept(CreaturesItems.MARABOU_SPAWN_EGG.get());
                entries.accept(CreaturesItems.CRANE_SPAWN_EGG.get());
                entries.accept(CreaturesItems.COCK_OF_THE_ROCK_SPAWN_EGG.get());
                entries.accept(CreaturesItems.TETRA_SPAWN_EGG.get());

            })
            .build());
}
