package com.frikinzi.creatures.registry;

import com.frikinzi.creatures.Creatures;
import com.frikinzi.creatures.entity.KakapoEntity;
import com.frikinzi.creatures.entity.LovebirdEntity;
import com.frikinzi.creatures.entity.MandarinDuckEntity;
import com.frikinzi.creatures.entity.SpoonbillEntity;
import com.frikinzi.creatures.entity.base.CreaturesBirdEntity;
import com.frikinzi.creatures.entity.egg.EggEntity;
import net.minecraft.world.entity.EntityType;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;
import net.minecraftforge.registries.RegistryObject;

@Mod.EventBusSubscriber(modid = Creatures.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ModEventSubscriber {
    private static final BiMap<Integer, EntityType<? extends CreaturesBirdEntity>> birdEntityMap = HashBiMap.create();

    @SubscribeEvent
    public static void registerEntityAttributes(EntityAttributeCreationEvent event) {
        event.put(CreaturesEntities.LOVEBIRD.get(), LovebirdEntity.createAttributes().build());
        event.put(CreaturesEntities.SPOONBILL.get(), SpoonbillEntity.createAttributes().build());
        event.put(CreaturesEntities.KAKAPO.get(), KakapoEntity.createAttributes().build());
//        event.put(CreaturesEntities.KOI.get(), KoiEntity.createAttributes().build());
//        event.put(CreaturesEntities.DOTTYBACK.get(), DottybackEntity.createAttributes().build());
//        event.put(CreaturesEntities.PIKE.get(), PikeEntity.createAttributes().build());
//        event.put(CreaturesEntities.GUPPY.get(), GuppyEntity.createAttributes().build());
        event.put(CreaturesEntities.MANDARIN_DUCK.get(), MandarinDuckEntity.createAttributes().build());
//        event.put(CreaturesEntities.AROWANA.get(), ArowanaEntity.createAttributes().build());
//        event.put(CreaturesEntities.RAVEN.get(), RavenEntity.createAttributes().build());
//        event.put(CreaturesEntities.SHRIMP.get(), ShrimpEntity.createAttributes().build());
//        event.put(CreaturesEntities.DOVE.get(), DoveEntity.createAttributes().build());
//        event.put(CreaturesEntities.RED_KITE.get(), RedKiteEntity.createAttributes().build());
//        event.put(CreaturesEntities.GOLDEN_EAGLE.get(), GoldenEagleEntity.createAttributes().build());
//        event.put(CreaturesEntities.SEA_EAGLE.get(), SeaEagleEntity.createAttributes().build());
//        event.put(CreaturesEntities.GYRFALCON.get(), GyrfalconEntity.createAttributes().build());
//        event.put(CreaturesEntities.LORIKEET.get(), LorikeetEntity.createAttributes().build());
//        event.put(CreaturesEntities.CONURE.get(), ConureEntity.createAttributes().build());
//        event.put(CreaturesEntities.FAIRYWREN.get(), FairywrenEntity.createAttributes().build());
//        event.put(CreaturesEntities.GHOST_CRAB.get(), GhostCrabEntity.createAttributes().build());
//        event.put(CreaturesEntities.GOURAMI.get(), GouramiEntity.createAttributes().build());
//        event.put(CreaturesEntities.PYGMY_FALCON.get(), PygmyFalconEntity.createAttributes().build());
//        event.put(CreaturesEntities.BARN_OWL.get(), BarnOwlEntity.createAttributes().build());
//        event.put(CreaturesEntities.WILD_DUCK.get(), WildDuckEntity.createAttributes().build());
//        event.put(CreaturesEntities.ROLLER.get(), RollerEntity.createAttributes().build());
//        event.put(CreaturesEntities.GOLDFISH.get(), GoldfishEntity.createAttributes().build());
//        event.put(CreaturesEntities.RANCHU.get(), RanchuEntity.createAttributes().build());
//        event.put(CreaturesEntities.CHICKADEE.get(), ChickadeeEntity.createAttributes().build());
//        event.put(CreaturesEntities.PYGMY_GOOSE.get(), PygmyGooseEntity.createAttributes().build());
//        event.put(CreaturesEntities.FIRE_GOBY.get(), FireGobyEntity.createAttributes().build());
//        event.put(CreaturesEntities.BLUE_TANG.get(), BlueTangEntity.createAttributes().build());
//        event.put(CreaturesEntities.TROUT.get(), TroutEntity.createAttributes().build());
//        event.put(CreaturesEntities.SWALLOW.get(), SwallowEntity.createAttributes().build());
//        event.put(CreaturesEntities.FIDDLER_CRAB.get(), FiddlerCrabEntity.createAttributes().build());
//        event.put(CreaturesEntities.FLAME_ANGELFISH.get(), FlameAngelfishEntity.createAttributes().build());
//        event.put(CreaturesEntities.IBIS.get(), IbisEntity.createAttributes().build());
//        event.put(CreaturesEntities.RED_SNAPPER.get(), RedSnapperEntity.createAttributes().build());
//        event.put(CreaturesEntities.WOOD_DUCK.get(), WoodDuckEntity.createAttributes().build());
//        event.put(CreaturesEntities.PEAFOWL.get(), PeafowlEntity.createAttributes().build());
//        event.put(CreaturesEntities.SPARROW.get(), SparrowEntity.createAttributes().build());
//        event.put(CreaturesEntities.BUSHTIT.get(), BushtitEntity.createAttributes().build());
//        event.put(CreaturesEntities.EAGLEOWL.get(), EagleOwlEntity.createAttributes().build());
//        event.put(CreaturesEntities.ROBIN.get(), RobinEntity.createAttributes().build());
//        event.put(CreaturesEntities.MAGPIE.get(), MagpieEntity.createAttributes().build());
//        event.put(CreaturesEntities.LAUGHINGTHRUSH.get(), LaughingthrushEntity.createAttributes().build());
//        event.put(CreaturesEntities.GOOSE.get(), GooseEntity.createAttributes().build());
//        event.put(CreaturesEntities.OSPREY.get(), OspreyEntity.createAttributes().build());
//        event.put(CreaturesEntities.KINGFISHER.get(), KingfisherEntity.createAttributes().build());
//        event.put(CreaturesEntities.PELICAN.get(), PelicanEntity.createAttributes().build());
//        event.put(CreaturesEntities.LAPWING.get(), LapwingEntity.createAttributes().build());
//        event.put(CreaturesEntities.SKUA.get(), SkuaEntity.createAttributes().build());
//        event.put(CreaturesEntities.BUNTING.get(), BuntingEntity.createAttributes().build());
//        event.put(CreaturesEntities.MONAL.get(), MonalEntity.createAttributes().build());
//        event.put(CreaturesEntities.TANAGER.get(), TanagerEntity.createAttributes().build());
//        event.put(CreaturesEntities.FINCH.get(), FinchEntity.createAttributes().build());
//        event.put(CreaturesEntities.VAMPIRECRAB.get(), VampireCrabEntity.createAttributes().build());
//        event.put(CreaturesEntities.TARANTULA.get(), TarantulaEntity.createAttributes().build());
//        event.put(CreaturesEntities.CAPERCAILLIE.get(), CapercaillieEntity.createAttributes().build());
//        event.put(CreaturesEntities.TIGERBARB.get(), TigerBarbEntity.createAttributes().build());
//        event.put(CreaturesEntities.PHEASANT.get(), PheasantEntity.createAttributes().build());
//        event.put(CreaturesEntities.ARAPAIMA.get(), ArapaimaEntity.createAttributes().build());
//        event.put(CreaturesEntities.PIRANHA.get(), PiranhaEntity.createAttributes().build());
//        event.put(CreaturesEntities.STORK.get(), StorkEntity.createAttributes().build());
//        event.put(CreaturesEntities.WHISTLINGDUCK.get(), WhistlingDuckEntity.createAttributes().build());
//        event.put(CreaturesEntities.GROUND_HORNBILL.get(), GroundHornbillEntity.createAttributes().build());
//        event.put(CreaturesEntities.SECRETARYBIRD.get(), SecretaryBirdEntity.createAttributes().build());
//        event.put(CreaturesEntities.SHOEBILL.get(), ShoebillEntity.createAttributes().build());
//        event.put(CreaturesEntities.STARLING.get(), StarlingEntity.createAttributes().build());
//        event.put(CreaturesEntities.TAMBAQUI.get(), TambaquiEntity.createAttributes().build());
//        event.put(CreaturesEntities.ELEPHANTNOSE.get(), ElephantNoseFishEntity.createAttributes().build());
//        event.put(CreaturesEntities.CORMORANT.get(), CormorantEntity.createAttributes().build());
//        event.put(CreaturesEntities.STINGRAY.get(), StingrayEntity.createAttributes().build());
//        event.put(CreaturesEntities.PUFFIN.get(), PuffinEntity.createAttributes().build());
//        event.put(CreaturesEntities.SAWFISH.get(), SawfishEntity.createAttributes().build());
//        event.put(CreaturesEntities.SEAGULL.get(), SeagullEntity.createAttributes().build());
//        event.put(CreaturesEntities.SWORDFISH.get(), SwordfishEntity.createAttributes().build());
//        event.put(CreaturesEntities.BOOBY.get(), BoobyEntity.createAttributes().build());
//        event.put(CreaturesEntities.SQUID.get(), SquidEntity.createAttributes().build());
//        event.put(CreaturesEntities.LOOKDOWN.get(), LookdownEntity.createAttributes().build());
//        event.put(CreaturesEntities.BANDED_PENGUIN.get(), BandedPenguinEntity.createAttributes().build());
//        event.put(CreaturesEntities.MANTIS_SHRIMP.get(), MantisShrimpEntity.createAttributes().build());
//        event.put(CreaturesEntities.RAIL.get(), RailEntity.createAttributes().build());
//        event.put(CreaturesEntities.BARRACUDA.get(), BarracudaEntity.createAttributes().build());
//        event.put(CreaturesEntities.AVOCET.get(), AvocetEntity.createAttributes().build());
//        event.put(CreaturesEntities.SEADRAGON.get(), SeaDragonEntity.createAttributes().build());
//        event.put(CreaturesEntities.TRUMPETFISH.get(), TrumpetfishEntity.createAttributes().build());
//        event.put(CreaturesEntities.CRESTED_PENGUIN.get(), CrestedPenguinEntity.createAttributes().build());
//        event.put(CreaturesEntities.PARROTFISH.get(), ParrotfishEntity.createAttributes().build());
//        event.put(CreaturesEntities.YELLOW_EYED_PENGUIN.get(), YellowEyedPenguinEntity.createAttributes().build());
//        event.put(CreaturesEntities.BRUSH_TAILED_PENGUIN.get(), BrushTailedPenguinEntity.createAttributes().build());
//        event.put(CreaturesEntities.LARGE_PENGUIN.get(), LargePenguinEntity.createAttributes().build());
//        event.put(CreaturesEntities.FRIGATE.get(), FrigateBirdEntity.createAttributes().build());
//        event.put(CreaturesEntities.CLOWNFISH.get(), ClownfishEntity.createAttributes().build());
//        event.put(CreaturesEntities.STILT.get(), StiltEntity.createAttributes().build());
//        event.put(CreaturesEntities.LUNGFISH.get(), LungfishEntity.createAttributes().build());
//        event.put(CreaturesEntities.LITTLE_PENGUIN.get(), LittlePenguinEntity.createAttributes().build());
//        event.put(CreaturesEntities.EDIBLE_CRAB.get(), EdibleCrabEntity.createAttributes().build());

        event.put(CreaturesEntities.EGG.get(), EggEntity.createAttributes().build());
    }

    public static void init() {
        birdEntityMap.put(0, CreaturesEntities.LOVEBIRD.get());
        birdEntityMap.put(1, CreaturesEntities.SPOONBILL.get());
        birdEntityMap.put(2, CreaturesEntities.KAKAPO.get());
        birdEntityMap.put(3, CreaturesEntities.MANDARIN_DUCK.get());
//        birdEntityMap.put(4, CreaturesEntities.RAVEN.get());
//        birdEntityMap.put(5, CreaturesEntities.DOVE.get());
//        birdEntityMap.put(6, CreaturesEntities.RED_KITE.get());
//        birdEntityMap.put(7, CreaturesEntities.GOLDEN_EAGLE.get());
//        birdEntityMap.put(8, CreaturesEntities.SEA_EAGLE.get());
//        birdEntityMap.put(9, CreaturesEntities.GYRFALCON.get());
//        birdEntityMap.put(10, CreaturesEntities.LORIKEET.get());
//        birdEntityMap.put(11, CreaturesEntities.CONURE.get());
//        birdEntityMap.put(12, CreaturesEntities.FAIRYWREN.get());
//        birdEntityMap.put(13, CreaturesEntities.PYGMY_FALCON.get());
//        birdEntityMap.put(14, CreaturesEntities.BARN_OWL.get());
//        birdEntityMap.put(15, CreaturesEntities.WILD_DUCK.get());
//        birdEntityMap.put(16, CreaturesEntities.ROLLER.get());
//        birdEntityMap.put(17, CreaturesEntities.CHICKADEE.get());
//        birdEntityMap.put(18, CreaturesEntities.PYGMY_GOOSE.get());
//        birdEntityMap.put(19, CreaturesEntities.SWALLOW.get());
//        birdEntityMap.put(20, CreaturesEntities.IBIS.get());
//        birdEntityMap.put(21, CreaturesEntities.WOOD_DUCK.get());
//        birdEntityMap.put(22, CreaturesEntities.PEAFOWL.get());
//        birdEntityMap.put(23, CreaturesEntities.SPARROW.get());
//        birdEntityMap.put(24, CreaturesEntities.BUSHTIT.get());
//        birdEntityMap.put(25, CreaturesEntities.EAGLEOWL.get());
//        birdEntityMap.put(26, CreaturesEntities.ROBIN.get());
//        birdEntityMap.put(27, CreaturesEntities.LAUGHINGTHRUSH.get());
//        birdEntityMap.put(28, CreaturesEntities.MAGPIE.get());
//        birdEntityMap.put(29, CreaturesEntities.GOOSE.get());
//        birdEntityMap.put(30, CreaturesEntities.OSPREY.get());
//        birdEntityMap.put(31, CreaturesEntities.KINGFISHER.get());
//        birdEntityMap.put(32, CreaturesEntities.PELICAN.get());
//        birdEntityMap.put(33, CreaturesEntities.LAPWING.get());
//        birdEntityMap.put(34, CreaturesEntities.SKUA.get());
//        birdEntityMap.put(35, CreaturesEntities.BUNTING.get());
//        birdEntityMap.put(36, CreaturesEntities.MONAL.get());
//        birdEntityMap.put(37, CreaturesEntities.TANAGER.get());
//        birdEntityMap.put(38, CreaturesEntities.FINCH.get());
//        birdEntityMap.put(39, CreaturesEntities.CAPERCAILLIE.get());
//        birdEntityMap.put(40, CreaturesEntities.PHEASANT.get());
//        birdEntityMap.put(41, CreaturesEntities.STORK.get());
//        birdEntityMap.put(42, CreaturesEntities.WHISTLINGDUCK.get());
//        birdEntityMap.put(43, CreaturesEntities.GROUND_HORNBILL.get());
//        birdEntityMap.put(44, CreaturesEntities.SECRETARYBIRD.get());
//        birdEntityMap.put(45, CreaturesEntities.SHOEBILL.get());
//        birdEntityMap.put(46, CreaturesEntities.STARLING.get());
//        birdEntityMap.put(47, CreaturesEntities.CORMORANT.get());
//        birdEntityMap.put(48, CreaturesEntities.PUFFIN.get());
//        birdEntityMap.put(49, CreaturesEntities.SEAGULL.get());
//        birdEntityMap.put(50, CreaturesEntities.BOOBY.get());
//        birdEntityMap.put(51, CreaturesEntities.BANDED_PENGUIN.get());
//        birdEntityMap.put(52, CreaturesEntities.RAIL.get());
//        birdEntityMap.put(53, CreaturesEntities.AVOCET.get());
//        birdEntityMap.put(54, CreaturesEntities.CRESTED_PENGUIN.get());
//        birdEntityMap.put(55, CreaturesEntities.YELLOW_EYED_PENGUIN.get());
//        birdEntityMap.put(56, CreaturesEntities.BRUSH_TAILED_PENGUIN.get());
//        birdEntityMap.put(57, CreaturesEntities.LARGE_PENGUIN.get());
//        birdEntityMap.put(58, CreaturesEntities.FRIGATE.get());
//        birdEntityMap.put(59, CreaturesEntities.STILT.get());
//        birdEntityMap.put(60, CreaturesEntities.LITTLE_PENGUIN.get());
        // etc...
    }
    public static BiMap<Integer, EntityType<? extends CreaturesBirdEntity>> getBirdEntityMap() {
        return birdEntityMap;
    }
}
